### ISSUE TITLE
Compiling Tuple{typeof(task_local_storage) try/catch is not supported.

### ISSUE THREAD

**Issue by cuber12** [SciML/DiffEqFlux.jl#561] opened 2021-05-24 16:00 UTC
Hi, I'm trying DiffEqFLux with GPU. I'm working with a small neural network, therefore it resides in the CPU memory, and only the ODE is solved on a GPU. First of all is it possible? if yes, can someone help me fix the following code?

```
using DifferentialEquations: ODEProblem, solve, Tsit5
using Flux, DiffEqFlux, Optim, OrdinaryDiffEq, DiffEqSensitivity

using CUDA
CUDA.allowscalar(false)

N = 1000

H0 = gpu(rand(Float32, N, N))
H1 = gpu(rand(Float32, N, N))

ann = Chain(Dense(1, 4, tanh), Dense(4, 4, tanh), Dense(4, 1))
θ = initial_params(ann)
p, re = Flux.destructure(ann)

function func!(dx, x, p, t)
    dx = H0*x
    dx += re(p)([t])[1]*H1*x
end

x0 = gpu(rand(Float32, N))
x1 = gpu(rand(Float32, N))

prob = ODEProblem(func!, x0, (0.0f0, 1.0f0))

function evolve(p)
    solve(prob, Tsit5(), p=p, save_start=false,
        save_everystep=false, abstol=1e-4, reltol=1e-4,
        sensealg=BacksolveAdjoint(autojacvec=ReverseDiffVJP(true))).u[1]
end

function cost(p)
    x = evolve(p)
    c = reduce(+, abs.(x - x1))
    println(c)
    c
end

res = DiffEqFlux.sciml_train(cost, p, ADAM(0.01), maxiters=20)
```

I get the following error

```
Compiling Tuple{typeof(task_local_storage), GPUArrays.var"#24#27"{CuArray{Float32, 1}}, Symbol, GPUArrays.ScalarIndexing}: try/catch is not supported.

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] instrument(ir::IRTools.Inner.IR)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/reverse.jl:121
  [3] #Primal#20
    @ ~/.julia/packages/Zygote/i1R8y/src/compiler/reverse.jl:202 [inlined]
  [4] Zygote.Adjoint(ir::IRTools.Inner.IR; varargs::Nothing, normalise::Bool)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/reverse.jl:315
  [5] _lookup_grad(T::Type)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/emit.jl:101
  [6] #s3008#1195
    @ ~/.julia/packages/Zygote/i1R8y/src/compiler/interface2.jl:34 [inlined]
  [7] var"#s3008#1195"(T::Any, j::Any, Δ::Any)
    @ Zygote ./none:0
  [8] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any, N} where N)
    @ Core ./boot.jl:571
  [9] macro expansion
    @ ~/.julia/packages/GPUArrays/Z5nPF/src/host/indexing.jl:83 [inlined]
 [10] Pullback
    @ ~/.julia/packages/GPUArrays/Z5nPF/src/host/mapreduce.jl:65 [inlined]
 [11] (::typeof(∂(#_mapreduce#21)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/interface2.jl:0
 [12] (::Zygote.var"#180#181"{Tuple{NTuple{5, Nothing}, Tuple{Nothing}}, typeof(∂(#_mapreduce#21))})(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/lib/lib.jl:194
 [13] (::Zygote.var"#1689#back#182"{Zygote.var"#180#181"{Tuple{NTuple{5, Nothing}, Tuple{Nothing}}, typeof(∂(#_mapreduce#21))}})(Δ::Float32)
    @ Zygote ~/.julia/packages/ZygoteRules/OjfTt/src/adjoint.jl:59
 [14] Pullback
    @ ~/.julia/packages/GPUArrays/Z5nPF/src/host/mapreduce.jl:34 [inlined]
 [15] (::typeof(∂(_mapreduce##kw)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/interface2.jl:0
 [16] (::Zygote.var"#180#181"{Tuple{NTuple{5, Nothing}, Tuple{}}, typeof(∂(_mapreduce##kw))})(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/lib/lib.jl:194
 [17] #1689#back
    @ ~/.julia/packages/ZygoteRules/OjfTt/src/adjoint.jl:59 [inlined]
 [18] Pullback
    @ ~/.julia/packages/GPUArrays/Z5nPF/src/host/mapreduce.jl:28 [inlined]
 [19] (::typeof(∂(#mapreduce#19)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/interface2.jl:0
 [20] #180
    @ ~/.julia/packages/Zygote/i1R8y/src/lib/lib.jl:194 [inlined]
 [21] #1689#back
    @ ~/.julia/packages/ZygoteRules/OjfTt/src/adjoint.jl:59 [inlined]
 [22] Pullback
    @ ~/.julia/packages/GPUArrays/Z5nPF/src/host/mapreduce.jl:28 [inlined]
 [23] (::typeof(∂(mapreduce)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/interface2.jl:0
 [24] Pullback
    @ ./reducedim.jl:359 [inlined]
 [25] (::typeof(∂(#reduce#674)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/interface2.jl:0
 [26] Pullback
    @ ./reducedim.jl:359 [inlined]
 [27] (::typeof(∂(reduce)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/interface2.jl:0
 [28] Pullback
    @ ./In[1]:34 [inlined]
 [29] (::typeof(∂(cost)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/interface2.jl:0
 [30] Pullback
    @ ~/.julia/packages/DiffEqFlux/GQl0U/src/train.jl:3 [inlined]
 [31] #180
    @ ~/.julia/packages/Zygote/i1R8y/src/lib/lib.jl:194 [inlined]
 [32] #1689#back
    @ ~/.julia/packages/ZygoteRules/OjfTt/src/adjoint.jl:59 [inlined]
 [33] Pullback
    @ ~/.julia/packages/SciMLBase/Z1NtH/src/problems/basic_problems.jl:107 [inlined]
 [34] #180
    @ ~/.julia/packages/Zygote/i1R8y/src/lib/lib.jl:194 [inlined]
 [35] #1689#back
    @ ~/.julia/packages/ZygoteRules/OjfTt/src/adjoint.jl:59 [inlined]
 [36] Pullback
    @ ~/.julia/packages/SciMLBase/Z1NtH/src/problems/basic_problems.jl:107 [inlined]
 [37] #180
    @ ~/.julia/packages/Zygote/i1R8y/src/lib/lib.jl:194 [inlined]
 [38] (::Zygote.var"#1689#back#182"{Zygote.var"#180#181"{Tuple{Tuple{Nothing, Nothing}, Int64}, typeof(∂(λ))}})(Δ::Float32)
    @ Zygote ~/.julia/packages/ZygoteRules/OjfTt/src/adjoint.jl:59
 [39] Pullback
    @ ~/.julia/packages/GalacticOptim/Ts0Bu/src/solve.jl:91 [inlined]
 [40] (::typeof(∂(λ)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/interface2.jl:0
 [41] (::Zygote.var"#69#70"{Zygote.Params, typeof(∂(λ)), Zygote.Context})(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/interface.jl:255
 [42] gradient(f::Function, args::Zygote.Params)
    @ Zygote ~/.julia/packages/Zygote/i1R8y/src/compiler/interface.jl:59
 [43] __solve(prob::OptimizationProblem{false, OptimizationFunction{false, GalacticOptim.AutoZygote, OptimizationFunction{true, GalacticOptim.AutoZygote, DiffEqFlux.var"#69#70"{typeof(cost)}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}, GalacticOptim.var"#148#158"{GalacticOptim.var"#147#157"{OptimizationFunction{true, GalacticOptim.AutoZygote, DiffEqFlux.var"#69#70"{typeof(cost)}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}, Nothing}}, GalacticOptim.var"#151#161"{GalacticOptim.var"#147#157"{OptimizationFunction{true, GalacticOptim.AutoZygote, DiffEqFlux.var"#69#70"{typeof(cost)}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}, Nothing}}, GalacticOptim.var"#156#166", Nothing, Nothing, Nothing}, Vector{Float32}, SciMLBase.NullParameters, Nothing, Nothing, Nothing, Base.Iterators.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:maxiters,), Tuple{Int64}}}}, opt::ADAM, data::Base.Iterators.Cycle{Tuple{GalacticOptim.NullData}}; maxiters::Int64, cb::Function, progress::Bool, save_best::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ GalacticOptim ~/.julia/packages/GalacticOptim/Ts0Bu/src/solve.jl:90
 [44] #solve#468
    @ ~/.julia/packages/SciMLBase/Z1NtH/src/solve.jl:3 [inlined]
 [45] sciml_train(::typeof(cost), ::Vector{Float32}, ::ADAM, ::GalacticOptim.AutoZygote; lower_bounds::Nothing, upper_bounds::Nothing, kwargs::Base.Iterators.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:maxiters,), Tuple{Int64}}})
    @ DiffEqFlux ~/.julia/packages/DiffEqFlux/GQl0U/src/train.jl:6
 [46] top-level scope
    @ In[2]:1
 [47] eval
    @ ./boot.jl:360 [inlined]
 [48] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1094
```

**Comment by ChrisRackauckas** [comment] 2021-05-24 16:20
It should be able to be made possible. It's a little tricky to make sure all of the right pieces end up on the CPU and GPU when it mixes like this though. I won't be able to take a look for a week.

**Comment by cuber12** [comment] 2021-06-13 17:56
@ChrisRackauckas could you please guide me on how to fix this issue? this will help us accelerate our simulations..

**Comment by ChrisRackauckas** [comment] 2021-06-14 15:18
Isolating it would be the most helpful thing. I don't think this necessarily needs the ODE in order to be recreated, so the best thing would be to find out how to simplify the ODE solver out of the example. If that doesn't seem possible, then what's the simplest ODE?

**Comment by cuber12** [comment] 2021-06-15 17:29
Thanks for your suggestion. We have a very high dimensional ODE that we hope to solve on a GPU, so I think we need an ODE here. In my opinion, this is the simplest ODE that is representative of our actual problem.

```using DifferentialEquations: ODEProblem, solve, Tsit5
using Flux, DiffEqFlux, Optim, OrdinaryDiffEq, DiffEqSensitivity

using CUDA
CUDA.allowscalar(false)

N = 2

H = gpu(rand(Float32, N, N))

ann = Chain(Dense(1, 4, tanh))
θ = initial_params(ann)
p, re = Flux.destructure(ann)

function func!(dx, x, p, t)
    dx = re(p)([t])[1]*H*x
end

x0 = gpu(rand(Float32, N))
x1 = gpu(rand(Float32, N))

prob = ODEProblem(func!, x0, (0.0f0, 1.0f0))

function evolve(p)
    solve(prob, Tsit5(), p=p, save_start=false,
          save_everystep=false, abstol=1e-4, reltol=1e-4,
          sensealg=BacksolveAdjoint(autojacvec=ReverseDiffVJP(true))).u[1]
end

function cost(p)
    x = evolve(p)
    c = reduce(+, abs.(x - x1))
    #println(c)
    c
end

res = DiffEqFlux.sciml_train(cost, p, ADAM(0.01), maxiters=20)

**Comment by ChrisRackauckas** [comment] 2021-06-16 10:57
>We have a very high dimensional ODE that we hope to solve on a GPU, so I think we need an ODE here.

That's not the question though. The question is, is the ODE solver adjoint involved in the issue, or is the issue more largely in the AD tooling? I.e., is it possible to recreate the same error without the ODE solver. The first step to figuring this out is to find out what exactly are the pieces causing it.

**Comment by cuber12** [comment] 2021-06-16 11:24
I see! actually I get the same error without ODE

```using Flux, DiffEqFlux, Optim

using CUDA
CUDA.allowscalar(false)

ann = Chain(Dense(1, 4, tanh))
p, re = Flux.destructure(ann)

x0 = gpu(rand(Float32, N))
x1 = gpu(rand(Float32, N))

function evolve(p)
   re(p)([1.0f0])[1]*x0
end

function cost(p)
    x = evolve(p)
    c = reduce(+, abs.(x - x1))
    println(c)
    c
end

res = DiffEqFlux.sciml_train(cost, p, ADAM(0.01), maxiters=20)

**Comment by ChrisRackauckas** [comment] 2021-06-16 11:32
I think the issue is that `c = reduce(+, abs.(x - x1))` hits some weird case on GPUs, whereas `c = sum(abs,x - x1)` has a good overload. This is probably worth reporting to CUDA.jl. 

Fixing that, now we get to something ODE related. I can see that your second issue is that ReverseDiff is not compatible with GPUs (as mentioned in https://diffeqflux.sciml.ai/dev/ControllingAdjoints/#Choosing-a-sensealg-in-a-Nutshell), so you need to reformulate this a bit in order to have GPU compatibility. But that won't get all of the way. Now `BacksolveAdjoint` requires concatenating the parameters and state space, so that won't be GPU-compatible. So `InterpolatingAdjoint` or `QuadratureAdjoint` with `ZygoteVJP` would have to be the solution here. And...

```julia
using Flux, DiffEqFlux, Optim, OrdinaryDiffEq, DiffEqSensitivity

using CUDA
CUDA.allowscalar(false)

N = 2

H = gpu(rand(Float32, N, N))

ann = Chain(Dense(1, 4, tanh))
θ = initial_params(ann)
p, re = Flux.destructure(ann)

function func(x, p, t)
    re(p)([t])[1]*H*x
end

x0 = gpu(rand(Float32, N))
x1 = gpu(rand(Float32, N))

prob = ODEProblem(func, x0, (0.0f0, 1.0f0))

function evolve(p)
    solve(prob, Tsit5(), p=p, save_start=false,
          save_everystep=false, abstol=1e-4, reltol=1e-4,
          sensealg=InterpolatingAdjoint()).u[1]
end

function cost(p)
    x = evolve(p)
    c = sum(abs,x - x1)
    #println(c)
    c
end

res = DiffEqFlux.sciml_train(cost, p, ADAM(0.01), maxiters=20)
```

this now fails with a DiffEqSensitivity issue, and I think the solution is that in the cost function it needs to bump the pullback to GPU via Adapt.jl. I'll work on this, but please upstream the `reduce` issue.

**Comment by ChrisRackauckas** [comment] 2021-06-16 12:12
The DiffEqSensitivity issue could be fixed with https://github.com/SciML/DiffEqSensitivity.jl/pull/424, but this reveals another issue.

```julia
using Flux, DiffEqFlux, Optim, OrdinaryDiffEq, DiffEqSensitivity

using CUDA
CUDA.allowscalar(false)
ann = Chain(Dense(1, 4, tanh))
p, re = Flux.destructure(ann)
x0 = gpu(rand(Float32, N))
_dy, back = Zygote.pullback(x0,p) do u,p
    vec(func(u, p, 0.0))
end
back(p)
```

```
GPU compilation of kernel broadcast_kernel(CUDA.CuKernelContext, CuDeviceMatrix{Float32, 1}, Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(*), Tuple{Base.Broadcast.Extruded{Vector{Float32}, Tuple{Bool}, Tuple{Int64}}, Base.Broadcast.Extruded{Adjoint{Float32, CuDeviceVector{Float32, 1}}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}}}, Int64) failed
KernelError: passing and using non-bitstype argument

Argument 4 to your kernel function is of type Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(*), Tuple{Base.Broadcast.Extruded{Vector{Float32}, Tuple{Bool}, Tuple{Int64}}, Base.Broadcast.Extruded{Adjoint{Float32, CuDeviceVector{Float32, 1}}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}}}, which is not isbits:
  .args is of type Tuple{Base.Broadcast.Extruded{Vector{Float32}, Tuple{Bool}, Tuple{Int64}}, Base.Broadcast.Extruded{Adjoint{Float32, CuDeviceVector{Float32, 1}}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}} which is not isbits.
    .1 is of type Base.Broadcast.Extruded{Vector{Float32}, Tuple{Bool}, Tuple{Int64}} which is not isbits.
      .x is of type Vector{Float32} which is not isbits.


check_invocation(job::GPUCompiler.CompilerJob) at validation.jl:66
macro expansion at driver.jl:318 [inlined]
macro expansion at TimerOutput.jl:226 [inlined]
macro expansion at driver.jl:317 [inlined]
emit_asm(job::GPUCompiler.CompilerJob, ir::LLVM.Module; strip::Bool, validate::Bool, format::LLVM.API.LLVMCodeGenFileType) at utils.jl:62
(::GPUCompiler.var"#emit_asm##kw")(::NamedTuple{(:format,), Tuple{LLVM.API.LLVMCodeGenFileType}}, ::typeof(GPUCompiler.emit_asm), job::GPUCompiler.CompilerJob, ir::LLVM.Module) at utils.jl:60
cufunction_compile(job::GPUCompiler.CompilerJob) at execution.jl:313
cached_compilation(cache::Dict{UInt64, Any}, job::GPUCompiler.CompilerJob, compiler::typeof(CUDA.cufunction_compile), linker::typeof(CUDA.cufunction_link)) at cache.jl:87
cufunction(f::GPUArrays.var"#broadcast_kernel#16", tt::Type{Tuple{CUDA.CuKernelContext, CuDeviceMatrix{Float32, 1}, Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(*), Tuple{Base.Broadcast.Extruded{Vector{Float32}, Tuple{Bool}, Tuple{Int64}}, Base.Broadcast.Extruded{Adjoint{Float32, CuDeviceVector{Float32, 1}}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}}}, Int64}}; name::Nothing, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}) at execution.jl:288
cufunction at execution.jl:282 [inlined]
macro expansion at execution.jl:102 [inlined]
#launch_heuristic#261 at gpuarrays.jl:17 [inlined]
launch_heuristic at gpuarrays.jl:17 [inlined]
copyto! at broadcast.jl:63 [inlined]
copyto! at broadcast.jl:936 [inlined]
copy at broadcast.jl:47 [inlined]
materialize at broadcast.jl:883 [inlined]
broadcast(::typeof(*), ::Vector{Float32}, ::Adjoint{Float32, CuArray{Float32, 1}}) at broadcast.jl:821
* at adjtrans.jl:302 [inlined]
#1525 at arraymath.jl:31 [inlined]
Thunk at thunks.jl:98 [inlined]
unthunk at thunks.jl:99 [inlined]
unthunk at thunks.jl:120 [inlined]
wrap_chainrules_output at chainrules.jl:41 [inlined]
map at tuple.jl:215 [inlined]
wrap_chainrules_output at chainrules.jl:42 [inlined]
ZBack at chainrules.jl:77 [inlined]
Pullback at operators.jl:560 [inlined]
(::typeof(∂(*)))(Δ::Vector{Float32}) at interface2.jl:0
Pullback at test.jl:38 [inlined]
(::typeof(∂(func)))(Δ::Vector{Float32}) at interface2.jl:0
Pullback at test.jl:65 [inlined]
(::Zygote.var"#41#42"{typeof(∂(#16))})(Δ::Vector{Float32}) at interface.jl:41
top-level scope at test.jl:67
eval at boot.jl:360 [inlined]
```

The problem is that the pullback vector there is not typed to match the state...

**Comment by ChrisRackauckas** [comment] 2021-06-16 12:15
Ahh, that's fundamental for InterpolatingAdjoint, because in that case you need the lambda pullback vector to match the state type, so it's going to have to pullback w.r.t. parameters (CPU) and get onto the GPU. So that little piece is an MWE for what's up with that adjoint.

But QuadratureAdjoint always keeps its vectors separate, so...

```julia
using Flux, DiffEqFlux, Optim, OrdinaryDiffEq, DiffEqSensitivity

using CUDA
CUDA.allowscalar(false)

N = 2

H = gpu(rand(Float32, N, N))

ann = Chain(Dense(1, 4, tanh))
θ = initial_params(ann)
p, re = Flux.destructure(ann)

function func(x, p, t)
    re(p)([t])[1]*H*x
end

x0 = gpu(rand(Float32, N))
x1 = gpu(rand(Float32, N))

prob = ODEProblem(func, x0, (0.0f0, 1.0f0))

function evolve(p)
    solve(prob, Tsit5(), p=p, save_start=false,
          save_everystep=false, abstol=1e-4, reltol=1e-4,
          sensealg=QuadratureAdjoint(autojacvec=ZygoteVJP())).u[1]
end

function cost(p)
    x = evolve(p)
    c = sum(abs,x - x1)
    #println(c)
    c
end

res = DiffEqFlux.sciml_train(cost, p, ADAM(0.01), maxiters=20)
```

that works with that latest PR.

**Comment by cuber12** [comment] 2021-06-16 12:24
Thanks a lot Chris :)

**Comment by ChrisRackauckas** [comment] 2021-06-16 19:25
Fixed with patch to DiffEqSensitivity.

**Closed by ChrisRackauckas** 2021-06-16 19:25 UTC
