### ISSUE TITLE
Neural ODE trains but throws an error when trying to show the result from Optim

### ISSUE THREAD

**Issue by John-Boik** [SciML/DiffEqFlux.jl#327] opened 2020-06-25 20:52 UTC
This is a followup to the closed issue [243](https://github.com/SciML/DiffEqFlux.jl/issues/243) of nearly the same name. I also cannot run script [Neural-ODE-Example-1](https://diffeqflux.sciml.ai/dev/GPUs/#Neural-ODE-Example-1) to completion. 

This is for the script that starts:
```
using DiffEqFlux, OrdinaryDiffEq, Flux, Optim, Plots, CuArrays, DiffEqSensitivity
CuArrays.allowscalar(false) # Makes sure no slow operations are occuring
```

After reaching the max number of iterations, I get the message:
```
 * Status: failure (reached maximum number of iterations)

 * Candidate solution
Error showing value of type Optim.MultivariateOptimizationResults{ADAM,Float64,CuArray{Float32,1,Nothing},Float64,Float32,Nothing,Bool}:
ERROR: scalar getindex is disallowed
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] assertscalar(::String) at /home/jboik/.julia/packages/GPUArrays/JqOUg/src/host/indexing.jl:41
 [3] getindex(::CuArray{Float32,1,Nothing}, ::Int64) at /home/jboik/.julia/packages/GPUArrays/JqOUg/src/host/indexing.jl:96
 [4] iterate at ./abstractarray.jl:913 [inlined]
 [5] iterate at ./abstractarray.jl:911 [inlined]
 [6] iterate at ./iterators.jl:641 [inlined]
 [7] iterate at ./iterators.jl:639 [inlined]
 [8] iterate at ./generator.jl:44 [inlined]
 [9] collect(::Base.Generator{Base.Iterators.Take{CuArray{Float32,1,Nothing}},Optim.var"#2#4"}) at ./array.jl:665
 [10] show(::IOContext{REPL.Terminals.TTYTerminal}, ::Optim.MultivariateOptimizationResults{ADAM,Float64,CuArray{Float32,1,Nothing},Float64,Float32,Nothing,Bool}) at /home/jboik/.julia/packages/Optim/L5T76/src/types.jl:242
 [11] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::Optim.MultivariateOptimizationResults{ADAM,Float64,CuArray{Float32,1,Nothing},Float64,Float32,Nothing,Bool}) at ./multimedia.jl:47
 [12] display(::REPL.REPLDisplay, ::MIME{Symbol("text/plain")}, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:137
 [13] display(::REPL.REPLDisplay, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:141
 [14] display(::Any) at ./multimedia.jl:323
 [15] (::Media.var"#15#16"{Optim.MultivariateOptimizationResults{ADAM,Float64,CuArray{Float32,1,Nothing},Float64,Float32,Nothing,Bool}})() at /home/jboik/.julia/packages/Media/ItEPc/src/compat.jl:28
 [16] hookless(::Media.var"#15#16"{Optim.MultivariateOptimizationResults{ADAM,Float64,CuArray{Float32,1,Nothing},Float64,Float32,Nothing,Bool}}) at /home/jboik/.julia/packages/Media/ItEPc/src/compat.jl:14
 [17] render(::Media.NoDisplay, ::Optim.MultivariateOptimizationResults{ADAM,Float64,CuArray{Float32,1,Nothing},Float64,Float32,Nothing,Bool}) at /home/jboik/.julia/packages/Media/ItEPc/src/compat.jl:27
 [18] render(::Optim.MultivariateOptimizationResults{ADAM,Float64,CuArray{Float32,1,Nothing},Float64,Float32,Nothing,Bool}) at /home/jboik/.julia/packages/Media/ItEPc/src/system.jl:160
 [19] display(::Media.DisplayHook, ::Optim.MultivariateOptimizationResults{ADAM,Float64,CuArray{Float32,1,Nothing},Float64,Float32,Nothing,Bool}) at /home/jboik/.julia/packages/Media/ItEPc/src/compat.jl:9
 [20] display(::Any) at ./multimedia.jl:323
 [21] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [22] invokelatest at ./essentials.jl:711 [inlined]
 [23] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:161
 [24] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:146
 [25] (::REPL.var"#do_respond#38"{Bool,REPL.var"#48#57"{REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:729
 [26] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [27] invokelatest at ./essentials.jl:711 [inlined]
 [28] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2354
 [29] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:1055
 [30] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:206
 [31] (::Base.var"#764#766"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:383
 [32] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [33] invokelatest at ./essentials.jl:711 [inlined]
 [34] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:367
 [35] exec_options(::Base.JLOptions) at ./client.jl:305
 [36] _start() at ./client.jl:484
```
 This is for a new Julia install with packages:

Dict{String,VersionNumber} with 13 entries:
  "Revise"                => v"2.7.3"
  "DiffEqSensitivity"     => v"6.23.0"
  "Atom"                  => v"0.12.15"
  "Optim"                 => v"0.21.0"
  "Juno"                  => v"0.8.2"
  "StochasticDiffEq"      => v"6.23.1"
  "CuArrays"              => v"2.2.2"
  "DiffEqFlux"            => v"1.16.0"
  "Flux"                  => v"0.10.4"
  "Plots"                 => v"1.4.3"
  "OrdinaryDiffEq"        => v"5.41.0"
  "Zygote"                => v"0.4.22"
  "DifferentialEquations" => v"6.14.0"

And using Julia:

Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) W-2195 CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

Also, I'm running the script (copied from the example) in a Linux command window using:
```include("./myscript.jl")```

I'm new to Julia, and not sure what I can do to fix the error, other than perhaps run on the CPU. But testing the GPU was my purpose.

John

**Comment by ChrisRackauckas** [comment] 2020-06-26 00:09
>Error showing value of type Optim.MultivariateOptimizationResults

It actually worked, but the `show` method doesn't work on that type. `Status: failure (reached maximum number of iterations)` is actually a success but it just ended by hitting the maximum number of iterations. The issue is just that upstream Optim prints something absolutely odd as the status. @pkofod could we get a quick fix to this? Since it's been awhile.

**Comment by ChrisRackauckas** [comment] 2020-06-26 00:58
Note that if you just do `res.minimizer` you'll see it just worked, so it's just an issue with the `show` command.

**Comment by ChrisRackauckas** [comment] 2020-06-26 14:10
Is fixed by https://github.com/SciML/DiffEqFlux.jl/pull/330 . Also @seadra that should fix the output issues you saw too.

**Closed** 2020-06-27 03:18 UTC
Labels: upstream
